import music1 from "./music1.mp3";
import music2 from "./music2.mp3";
import music3 from "./music3.mp3";
import music4 from "./music4.mp3";
import music5 from "./music5.mp3";
import music6 from "./music6.mp3";
import music7 from "./music7.mp3";
import music8 from "./music8.mp3";
import music9 from "./music9.mp3";
import music10 from "./music10.mp3";
import music11 from "./music11.mp3";
import music12 from "./music12.mp3";
import music13 from "./music13.mp3";
import animalS1 from "./Asu.m4a";
import animalS2 from "./Baka.m4a";
import animalS3 from "./manuk.m4a";
import animalS4 from "./Dagis.m4a";
import animalS5 from "./Babi.m4a";
import animalS6 from "./Dangki.m4a";
import animalS7 from "./Talubang,mariposa.m4a";
import animalS8 from "./Gayda,elepanti.m4a";
import animalS9 from "./Tugak.m4a";
import animalS10 from "./Kambing.m4a";
import animalS11 from "./Kabayu.m4a";
import animalS12 from "./Leun.m4a";
import animalS13 from "./Limpasut,pating.m4a";
import animalS14 from "./Tupa.m4a";
import animalS15 from "./ubinganlubingan.m4a";
import animalS16 from "./lombalombabalyena.m4a";
import phraseS1 from "./nanu.m4a";
import phraseS2 from "./kapilan.m4a";
import phraseS3 from "./nokarin.m4a";
import phraseS4 from "./magkanu.m4a";
import phraseS5 from "./taga nukarin ka.m4a";
import phraseS6 from "./mawawala ku.m4a";
import phraseS7 from "./ali ku aintindyan.m4a";
import phraseS8 from "./mayap a abak.m4a";
import phraseS9 from "./mayap a abak pu.m4a";
import phraseS10 from "./mayap a gatpanapun.m4a";
import phraseS11 from "./mayap a gatpanapun pu.m4a";
import phraseS12 from "./mayap a bengi.m4a";
import phraseS13 from "./mayap a bengi pu.m4a";
import phraseS14 from "./komusta.m4a";
import phraseS15 from "./komusta kayu pu.m4a";
import phraseS16 from "./salamat.m4a";
import phraseS17 from "./salamat pu.m4a";
import phraseS18 from "./alang nanu man.m4a";
import phraseS19 from "./alang nanu man pu.m4a";
import numberS1 from "./metunng.m4a";
import numberS2 from "./Adwa.m4a";
import numberS3 from "./Atlu.m4a";
import numberS4 from "./apat.m4a";
import numberS5 from "./Lima.m4a";
import numberS6 from "./Anam.m4a";
import numberS7 from "./Pitu.m4a";
import numberS8 from "./Walu.m4a";
import numberS9 from "./siam.m4a";
import numberS10 from "./Apulu.m4a";
import colorS1 from "./mairo.m4a";
import colorS2 from "./tayum.m4a";
import colorS3 from "./aluntianng.m4a";
import colorS4 from "./kuliawan.m4a";
import colorS5 from "./diwa.m4a";
import colorS6 from "./komanggi.m4a";
import colorS7 from "./ubi.m4a";
import colorS8 from "./abu.m4a";
import colorS9 from "./dilo.m4a";
import colorS10 from "./malutu.m4a";
import colorS11 from "./tuling.m4a";
import fruitVegS1 from "./ubas.m4a";
import fruitVegS2 from "./Kalamunding.m4a";
import fruitVegS3 from "./payungpayung.m4a";
import fruitVegS4 from "./sibuyas.m4a";
import fruitVegS5 from "./peras.m4a";
import fruitVegS6 from "./apol.m4a";
import fruitVegS7 from "./saging.m4a";
import fruitVegS8 from "./ripolyu.m4a";
import fruitVegS9 from "./carrot.m4a";
import fruitVegS10 from "./mais.m4a";
import fruitVegS11 from "./pinya.m4a";
import fruitVegS12 from "./patatas.m4a";
import fruitVegS13 from "./kulubasa.m4a";
import fruitVegS14 from "./istroberi.m4a";
import fruitVegS15 from "./kamatis.m4a";
import genVocabS1 from "./pagkeran.m4a";
import genVocabS2 from "./bisikleta.m4a";
import genVocabS3 from "./ayup.m4a";
import genVocabS4 from "./libru.m4a";
import genVocabS5 from "./kandila.m4a";
import genVocabS6 from "./kotsi.m4a";
import genVocabS7 from "./asan.m4a";
import genVocabS8 from "./bulaklak.m4a";
import genVocabS9 from "./bale.m4a";
import genVocabS10 from "./pulo.m4a";
import genVocabS11 from "./llave.m4a";
import genVocabS12 from "./diaryu.m4a";
import genVocabS13 from "./lapis.m4a";
import genVocabS14 from "./tanaman.m4a";
import genVocabS15 from "./bunduk.m4a";
import genVocabS16 from "./tete.m4a";
import genVocabS17 from "./boti.m4a";
import bgMusic from "./bgMusic.mp3";

export { music1, music2, music3, music4, music5, music6, music7, music8, music9, music10, music11, music12, music13, animalS1, animalS2, animalS3, animalS4, animalS5, animalS6, animalS7, animalS8, animalS9, animalS10, animalS11, animalS12, animalS13, animalS14, animalS15, animalS16, phraseS1, phraseS2, phraseS3, phraseS4, phraseS5, phraseS6, phraseS7, phraseS8, phraseS9, phraseS10, phraseS11, phraseS12, phraseS13, phraseS14, phraseS15, phraseS16, phraseS17, phraseS18, phraseS19, numberS1, numberS2, numberS3, numberS4, numberS5, numberS6, numberS7, numberS8, numberS9, numberS10, colorS1, colorS2, colorS3, colorS4, colorS5, colorS6, colorS7, colorS8, colorS9, colorS10, colorS11, fruitVegS1, fruitVegS2, fruitVegS3, fruitVegS4, fruitVegS5, fruitVegS6, fruitVegS7, fruitVegS8, fruitVegS9, fruitVegS10, fruitVegS11, fruitVegS12, fruitVegS13, fruitVegS14, fruitVegS15, genVocabS1, genVocabS2, genVocabS3, genVocabS4, genVocabS5, genVocabS6, genVocabS7, genVocabS8, genVocabS9, genVocabS10, genVocabS11, genVocabS12, genVocabS13, genVocabS14, genVocabS15, genVocabS16, genVocabS17, bgMusic };
